{% set version = "1.9.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-readbrukerflexdata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/readBrukerFlexData_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/readBrukerFlexData/readBrukerFlexData_{{ version }}.tar.gz
  sha256: 6752db50a9ac52ac58ba035c1f14064c601ce2bee9a8614e4d4327acbace182e

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('readBrukerFlexData')"           # [not win]
    - "\"%R%\" -e \"library('readBrukerFlexData')\""  # [win]

about:
  home: http://strimmerlab.org/software/maldiquant/ https://github.com/sgibb/readBrukerFlexData/
  license: GPL-3.0-or-later
  summary: Reads data files acquired by Bruker Daltonics' matrix-assisted laser desorption/ionization-time-of-flight mass spectrometer of the *flex series.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ArneKr
    - FrodePedersen
    - MathiasHaudgaard

# Package: readBrukerFlexData
# Version: 1.8.5
# Date: 2017-04-22
# Title: Reads Mass Spectrometry Data in Bruker *flex Format
# Authors@R: person("Sebastian", "Gibb", role=c("aut", "cre"), email="mail@sebastiangibb.de")
# Depends: R (>= 3.3.0)
# Description: Reads data files acquired by Bruker Daltonics' matrix-assisted laser desorption/ionization-time-of-flight mass spectrometer of the *flex series.
# License: GPL (>= 3)
# URL: http://strimmerlab.org/software/maldiquant/ https://github.com/sgibb/readBrukerFlexData/
# BugReports: https://github.com/sgibb/readBrukerFlexData/issues/
# LazyLoad: yes
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-04-22 14:54:43 UTC; sebastian
# Author: Sebastian Gibb [aut, cre]
# Maintainer: Sebastian Gibb <mail@sebastiangibb.de>
# Repository: CRAN
# Date/Publication: 2017-04-22 16:20:33 UTC
