travis:
  secure:
    BINSTAR_TOKEN: KhNcDGoRhXwjiH1wm96AVxYK91EbSkqqC6S62JuC5I7EkQKCMc/297cMHDn8p3aYKY1vlxzgLacj4xk/WJDcdYI/8GXv6TjmboSUNxRP4vhfLvZc6x1wbX7uJni91cuaEsVsTcGfwraxsnXjlTiQv5Ne6kfGLcegR+bLS36VkUqDcROkF1LwRnuH7iInuS5lDZahStFjqn7sUt6CtrjX+byx+YOTrkvGyg5vphVjrzaCH7JRtmZpnaq/mh4DoeLUdyd2ID5QsUIQqgup2lr2NU8sMUjqjLSz/O6kzyqRGFP2Dk6LE5KE56ZsjiXdKi1VEN31L2P0oEFpZi+TjwEy772c7d25njEh+CFapSnHy9tYAAqft3CtIabhJHhz9kx0d2QYeC/ZxXvIU7lmN6ppwvhaLwiPEndPcqfJYvL+aPgjAgrbMPj8Et6m9VCxl7BdzbCBjLEzqj96+cXBePHjXYu1ozPFDvebS/B0fNq53ji82iXjLTC8sncSY07+fiqFkyRvzU23CWvJDkjELypzRPe3gLKBRX8uz0tcYg86MVc2oeGuhp9oiUhS3i7K+V2Jq0FoLPG+bsu+kqDMZgBqdqwVvQeZ4O6F8gaceBYv4widiEU7Qd6P2vUgyDio88tVEEXJbxdKlDj6AbzJNN5lvX83OdNH13hiuZX3+R8UdoU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
