appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mSOlpKEYpDbOz8enjno0yYkI4JH0YIpV7jA0ZibQ0Z1nOA00VDN1F5ipTrdY99FOVNbBdMkOzZADPg/eyrWmDDAV05nwEwzyxv3ntgjvb3xHag0Cx1rYApqPOuCpQC+PD0Ol4MkOYnghjShT6xxDKuyzQdklnxg6C4jKVHTEgZWxPm0CU2iJejxffX0URywUKIAh6gb3+l3bUZJzcB40awFDis7/tsG84btka1yO/o+2Mgjfl/iomya//4M3MHufgzuySNXbKZPikYBz793MhTxs1/xS4AWSJUb/sd+Jyf6oDlwym2QmkpR9dRHxPXchOXjV0yPbQXDN616g1gR7XYlqTumidFnOOSWFD35kvIh4EFZcb/OoSx6Szn4tsd8hWzt5MeQ4JCfF6eIAoLnZhpsu6NcZjMdmtufcgq20C/CgCS05idMqhSM4mZ1o72ZLZJsYkMGNryRxVkB5L/BDH2kNbw/2VQ94qCqCSefBJs2qx0+mQiKJPDH2SOyCTzVVCcVZmTVRg3blTd1Km+6E/dBhtp54rKtRTTD3Jx+Ek6Q1XDXgkpp0vm74ApPwxB3SuIs+UlzMXol6/FtQrUpHlqOId3pNAnkF7OkY8RjSWDvil3Ncf4kdIXV+pPbT3uFSNr2bZYgMSmGAfVUYEshgpxG80zukPIrqbQuxFbgmKts=}
